### ISSUE TITLE
Cleanup environment variables

### ISSUE THREAD

**Issue by soumyaray** [soafloggers/movlog#2]
I got your application (bin/movlog) working by just changing one line: https://github.com/soafloggers/movlog/blob/master/lib/movlog/omdb_api.rb#L26

changed to: `t: t,` so that i just use the method parameter instead of checking env variable.

also, i  think you can remove all config, config= business from your omdbapi class -- the keyword is not a secret!

**Comment by aditya-utama-wijaya** [comment]
Prof., thank you for your post here.
We were thinking to provide credentials to each of the APIs so that we can apply things we learn from you in the class (only as a practice), but of course in the end we would remove the keyword from the credential file, and maybe this is the time to do it.
:)
Thanks.

**Comment by soumyaray** [comment]
Great!  Super proud of your team to try it out nonetheless!


On October 29, 2016 at 15:53:06 PM, Aditya Utama Wijaya (
notifications@github.com) wrote:

Prof., thank you for your post here.
We were thinking to provide credentials to each of the APIs so that we can
apply things we learn from you in the class (only as a practice), but of
course in the end we would remove the keyword from the credential file, and
maybe this is the time to do it.
:)
Thanks.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/soafloggers/movlog/issues/2#issuecomment-257077661>,
or mute
the thread

**Comment by soumyaray** [comment]
Feel free to close this issue once you've made the requisite changes
